name: run main.py

on:
  schedule:
    - cron: '30 14 * * *'  # 14:30 UTC = 23:30 KST
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: python main.py

      - name: Ensure trailing newline in README
        run: |
          sed -i -e '$a\' README.md

      - name: Update README with current time
        run: |
          CURRENT_TIME=$(TZ="Asia/Seoul" date '+%d/%m/%Y %H.%M')
          if grep -q "Último check:" README.md; then
            sed -i "s|Último check: .*|Último check: $CURRENT_TIME (hora corea)|" README.md
          else
            echo -e "\nÚltimo check: $CURRENT_TIME (hora corea)" >> README.md
          fi
          
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
