name: Automated Python Script Execution with README Update

on:
  schedule:
    - cron: '30 14 * * *'  # 14:30 UTC = 23:30 KST
  workflow_dispatch:

jobs:
  execute-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main  # Asegurar que estamos en la rama correcta

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Update README timestamp
        run: |
          CURRENT_TIME=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
          sed -i "s/Última revisión:.*/Última revisión: \`${CURRENT_TIME}\`/" README.md

      - name: Execute main script
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python main.py

      - name: Commit and Push changes
        if: success()
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Actions"
          git add -A
          git diff --staged --quiet || git commit -m "Actualización automática [skip ci]"
          git push origin main
